### ISSUE TITLE
Error: Cannot find module '../../package.json'

### ISSUE THREAD

**Issue by manindertaggar** [inventaire/wikidata-subset-search-engine#2]
cat latest-all.json | wdfilter --claim P31:Q5 --omit type,claims,sitelinks | import_to_elastic humans
----------------------------------------------------------------
 module.js:472
    throw err;
    ^

Error: Cannot find module '../../package.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/media/data/server/similarist/wikidata-subset-search-engine/node_modules/wikidata-filter/lib/program.js:2:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
TypeError: Cannot read property 'bind' of undefined
    at Object.<anonymous> (/media/data/server/similarist/wikidata-subset-search-engine/lib/import.coffee:45:19)
    at Object.<anonymous> (/media/data/server/similarist/wikidata-subset-search-engine/lib/import.coffee:2:1)
    at Module._compile (module.js:571:32)
    at Object.exports.run (/media/data/server/similarist/wikidata-subset-search-engine/node_modules/coffee-script/lib/coffee-script/coffee-script.js:173:23)
    at compileScript (/media/data/server/similarist/wikidata-subset-search-engine/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
    at compilePath (/media/data/server/similarist/wikidata-subset-search-engine/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
    at Object.exports.run (/media/data/server/similarist/wikidata-subset-search-engine/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
    at Object.<anonymous> (/media/data/server/similarist/wikidata-subset-search-engine/node_modules/coffee-script/bin/coffee:7:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

**Comment by maxlath** [comment]
thanks for reporting, it was a [bug in wikidata-filter](https://github.com/maxlath/wikidata-filter/commit/40b61c21a2abcea2736fca3d47cc35e406f405fa), I thus [updated wikidata-subset-search-engine to the new patched version](https://github.com/inventaire/wikidata-subset-search-engine/commit/4caaa637e3be94c02693b892452105f02f0dc8ed) where it should now be fine.

**Comment by manindertaggar** [comment]
thanks for solving that maxlath,
after updating and running same command i get following error

TypeError: Cannot read property 'bind' of undefined
    at Object.<anonymous> (/media/data/server/similarist/wikidata-subset-search-engine/lib/import.coffee:45:19)
    at Object.<anonymous> (/media/data/server/similarist/wikidata-subset-search-engine/lib/import.coffee:2:1)
    at Module._compile (module.js:571:32)
    at Object.exports.run (/media/data/server/similarist/wikidata-subset-search-engine/node_modules/coffee-script/lib/coffee-script/coffee-script.js:173:23)
    at compileScript (/media/data/server/similarist/wikidata-subset-search-engine/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
    at compilePath (/media/data/server/similarist/wikidata-subset-search-engine/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
    at Object.exports.run (/media/data/server/similarist/wikidata-subset-search-engine/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
    at Object.<anonymous> (/media/data/server/similarist/wikidata-subset-search-engine/node_modules/coffee-script/bin/coffee:7:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

**Comment by maxlath** [comment]
should now have been fixed by ed7444d
